substitutions:
  devicename: haustuer_display
  human_devicename: Display Haust√ºr

packages:
  wifi: !include includes/wifi.yaml
  common: !include includes/common.yaml

esphome:
  includes:
    - includes/custom_components/DisplayHaustuerComponent.h
    - includes/lib/GFX4dIoD9.cpp
    - includes/lib/GFX4dIoD9.h

esp8266:
  board: gen4iod

api:
    
logger:

sensor:
  - platform: homeassistant
    name: "Forecast Temp"
    entity_id: sensor.dwd_weather_augsburg_temperature
    id: forecast_temp_sensor
    internal: true

text_sensor:
  - platform: homeassistant
    name: "Forecast"
    entity_id: weather.dwd_weather_augsburg
    id: forecast_sensor
    internal: true
  - platform: homeassistant
    name: "Person active"
    entity_id: person.markus
    id: person_active_sensor
    internal: true

custom_component:
  - lambda: return {new DisplayHaustuerComponent()};
